const val BAMBOO_SYMBOL = 's'
const val CHARACTER_SYMBOL = 'm'
const val DOT_SYMBOL = 'p'
const val DRAGON_SYMBOL = 'z'
const val WIND_SYMBOL = 'z'
val SYMBOL_ORDER = arrayOf(BAMBOO_SYMBOL, CHARACTER_SYMBOL, DOT_SYMBOL, DRAGON_SYMBOL)
var SUIT_SYMBOL_ORDER = arrayOf(BAMBOO_SYMBOL, CHARACTER_SYMBOL, DOT_SYMBOL)
const val HONOR_SYMBOL = 'z'